baseURL = "http://localhost"
languageCode = "en"
DefaultContentLanguage = "en"
title = "My Blog"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe=true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[related]
includeNewer = true
threshold = 80
toLower = true
[[related.indices]]
name = 'keywords'
weight = 100
[[related.indices]]
name = 'tags'
weight = 80


[params]
    title = "I love mathematics"
    author = "Ryousuke Kaga"
    #copyright = "2020-2021"
    description = "🇯🇵/ Kaga Ryousuke / 17 / learning computer science / looking for job opportunities"
    profilePicture = "images/profile.jpg"
    keywords = ""
    favicon = "favicons/"
    # example ["css/custom.css"]
    customCss = []
    # example ["js/custom.js"]
    customJs = []
    mainSections = ["post"]
    images = ["images/site-feature-image.png"]
    doNotLoadAnimations = false
    # Form Spree Contact Form
    #contactFormAction = "https://formspree.io/f/your-form-hash-here"
    #contactFormReCaptcha = "your-site-key-here"
    # Google Fonts
    #googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
    # Google Site Verify
    #googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    singleDateFormat = "2/1/2006"
    indexDateFormat = "2/1/2006"
    listDateFormat = "2/1/2006"
    # Commento Comments
    # CommentoURL = "https://commento.example.com/js/commento.js"
    # Read More links for truncated summaries
    # readMore = true
    # postSectionName = "blog"
    # relatedPosts = true
    # numberOfRelatedPosts = 3


    reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

    # hidesidebar = true

    [params.simpleAnalytics]
    # enable = true
    # customurl = "https://analytics.example.com"

    [params.plausibleAnalytics]
    # domain = "example.com"
    # serverURL = "https://analytics.example.com"

    [params.umami]
    # serverURL = "example.com"
    # id = "94db1cb1-74f4-4a40-ad6c-962362670409"
    # trackerScriptName = "mycustomscriptname.js"

    ## Math settings
    [params.math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

    ## Social links
    # use 'fab' when brand icons, use 'fas' when standard solid icons.
    [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/blairablake"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/thecatblake/"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "k222ryousuke@gmail.com"

    [mermaid]
    # enable = true

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Portfolio"
weight = 300
identifier = "portfolio"
url = "/portfolio/"

[[menu.main]]
name = "About"
weight = 400
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Accomplishments"
weight = 500
identifier = "accomplishments"

[[menu.main]]
name = "Awards"
weight = 510
identifier = "awards"
url = "/awards/"
parent = "accomplishments"

[[menu.main]]
name = "Certifications"
weight = 520
identifier = "certifications"
url = "/certifications/"
parent = "accomplishments"

[[menu.main]]
name = "Contact"
weight = 600
identifier = "contact"
url = "/contact/"

[[menu.footer]]
name = "imprint"
weight = 1
identifier = "imprint"
url = "/imprint/"

[languages]
[languages.en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[languages.ar]
title = "فلانة الفلانية"
description = "أنا أعمل كمطورة ويب في شركة س"
contentDir = "content/arabic"
weight = 2
LanguageDirection = "rtl"
LanguageName = "AR"
